FROM ubuntu
RUN apt-get update -y && apt-get install iperf3 -y

ADD entrypoint-client.sh /usr/local/bin/entrypoint-client.sh
RUN chmod +x /usr/local/bin/entrypoint-client.sh

EXPOSE 5201
ENTRYPOINT ["entrypoint-client.sh"]
